### ISSUE TITLE
Sentry Issue - /opt/sitemap/sitemap.xml:1:0: no element found

### ISSUE THREAD

**Issue by c-schwarze** [betheluniversity/cascade-cron#18]
The last few days, this sentry error has been thrown. I'm guessing it has to do with the validate xml, since it appears that sitemap.xml is being generated properly.

@bam95899 can you take a look at this when you have a chance?

**Comment by bam95899** [comment]
Issue fixed in PR #20

**Comment by c-schwarze** [comment]
Closing, since #20 is being merged in.
